# Generated by Django 3.1.3 on 2020-11-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'sities'},
        ),
    ]
